#!/usr/bin/env python
# -*- encoding: utf-8 -*-

from __future__ import print_function # Python 2/3 compatibility

import json

try:
    import boto3
except:
    import boto as boto3


def main():
    message = {
        "AlarmName": "WordpressKidzania4xx",
        "AlarmDescription": "4xx HTTP code from ELB",
        "AWSAccountId": "289061955845",
        "NewStateValue": "ALARM",
        "NewStateReason": "Threshold Crossed: 1 datapoint [2.0 (18/07/17 05:07:00)] was greater than the threshold (0.0).",
        "StateChangeTime": "2017-07-18T05:08:27.787+0000",
        "Region": "Asia Pacific - Tokyo",
        "OldStateValue": "OK",
        "Trigger": {
            "MetricName": "HTTPCode_ELB_4XX_Count",
            "Namespace": "AWS/ApplicationELB",
            "StatisticType": "Statistic",
            "Statistic": "SUM",
            "Unit": null,
            "Dimensions": [
            {
                "name": "LoadBalancer",
                "value": "app/prd-wordpress-kidzania/5ffd2fc530f4e66f"
            }
            ],
            "Period": 60,
            "EvaluationPeriods": 1,
            "ComparisonOperator": "GreaterThanThreshold",
            "Threshold": 0,
            "TreatMissingData": "- TreatMissingData: NonBreaching",
            "EvaluateLowSampleCountPercentile": ""
        }
        }


if __name__ == "__main__":
    main()
